version: '3.8'

networks:
  tams-network:
    driver: bridge

services:
  nginx:
    build: ./nginx-docker
    image: nginx-ssl
    container_name: nginx-ssl
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/build:/var/www/html/tams/build/:ro
    depends_on:
      - backend
    networks:
      - tams-network

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: ta
    ports:
      - "3306:3306"
    networks:
      - tams-network

  node:
    build: ./backend 
    image: node
    container_name: node
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - tams-network
