networks:
  tams-network:
    driver: bridge

services:
  nginx:
    build: ./nginx-docker
    image: nginx-ssl
    container_name: nginx-ssl
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-docker/public_html:/var/www/html/digid:ro
      - ./nginx-docker/nginx-config:/etc/nginx/conf.d:ro
      - ./nginx-docker/nginx-config/ssl:/etc/nginx/ssl:ro
      - ./nginx-docker/nginx-config/ssl:/etc/ssl/digid:ro
    networks:
      - tams-network
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
    image: tams-frontend
    container_name: tams-frontend
    ports:
      - "3000:80"
    networks:
      - tams-network

  backend:
    build: ./backend
    image: tams-backend
    container_name: tams-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - tams-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: ta
    ports:
      - "3306:3306"
    networks:
      - tams-network
